/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as InviterRouteImport } from './routes/inviter'
import { Route as CarteRouteImport } from './routes/carte'
import { Route as MondeRouteImport } from './routes/monde'
import { Route as ExpeditionRouteImport } from './routes/expedition'
import { Route as VoteRouteImport } from './routes/vote'
import { Route as ProfilRouteImport } from './routes/profil'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const InviterRoute = InviterRouteImport.update({
  id: '/inviter',
  path: '/inviter',
  getParentRoute: () => rootRouteImport,
} as any)
const CarteRoute = CarteRouteImport.update({
  id: '/carte',
  path: '/carte',
  getParentRoute: () => rootRouteImport,
} as any)
const MondeRoute = MondeRouteImport.update({
  id: '/monde',
  path: '/monde',
  getParentRoute: () => rootRouteImport,
} as any)
const ExpeditionRoute = ExpeditionRouteImport.update({
  id: '/expedition',
  path: '/expedition',
  getParentRoute: () => rootRouteImport,
} as any)
const VoteRoute = VoteRouteImport.update({
  id: '/vote',
  path: '/vote',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfilRoute = ProfilRouteImport.update({
  id: '/profil',
  path: '/profil',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/inviter': typeof InviterRoute
  '/carte': typeof CarteRoute
  '/monde': typeof MondeRoute
  '/expedition': typeof ExpeditionRoute
  '/vote': typeof VoteRoute
  '/profil': typeof ProfilRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/inviter': typeof InviterRoute
  '/carte': typeof CarteRoute
  '/monde': typeof MondeRoute
  '/expedition': typeof ExpeditionRoute
  '/vote': typeof VoteRoute
  '/profil': typeof ProfilRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/inviter': typeof InviterRoute
  '/carte': typeof CarteRoute
  '/monde': typeof MondeRoute
  '/expedition': typeof ExpeditionRoute
  '/vote': typeof VoteRoute
  '/profil': typeof ProfilRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/inviter' | '/carte' | '/monde' | '/expedition' | '/vote' | '/profil'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/inviter' | '/carte' | '/monde' | '/expedition' | '/vote' | '/profil'
  id: '__root__' | '/' | '/inviter' | '/carte' | '/monde' | '/expedition' | '/vote' | '/profil'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  InviterRoute: typeof InviterRoute
  CarteRoute: typeof CarteRoute
  MondeRoute: typeof MondeRoute
  ExpeditionRoute: typeof ExpeditionRoute
  VoteRoute: typeof VoteRoute
  ProfilRoute: typeof ProfilRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inviter': {
      id: '/inviter'
      path: '/inviter'
      fullPath: '/inviter'
      preLoaderRoute: typeof InviterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/carte': {
      id: '/carte'
      path: '/carte'
      fullPath: '/carte'
      preLoaderRoute: typeof CarteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/monde': {
      id: '/monde'
      path: '/monde'
      fullPath: '/monde'
      preLoaderRoute: typeof MondeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/expedition': {
      id: '/expedition'
      path: '/expedition'
      fullPath: '/expedition'
      preLoaderRoute: typeof ExpeditionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vote': {
      id: '/vote'
      path: '/vote'
      fullPath: '/vote'
      preLoaderRoute: typeof VoteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profil': {
      id: '/profil'
      path: '/profil'
      fullPath: '/profil'
      preLoaderRoute: typeof ProfilRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  InviterRoute: InviterRoute,
  CarteRoute: CarteRoute,
  MondeRoute: MondeRoute,
  ExpeditionRoute: ExpeditionRoute,
  VoteRoute: VoteRoute,
  ProfilRoute: ProfilRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
